name: Build and Deploy Static Mkdocs Documentation

# Controls when the action will run. Triggers the workflow on pull request
on:
  push:
    branches:
      - main
    paths:
      - 'mkdocs.yml'
      - 'src/schema/*.yaml'
      - 'src/docs/*'

  repository_dispatch:
    types: trigger-build-deploy-documentation

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  github-pages:
    runs-on: ubuntu-latest
    
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        
      #----------------------------------------------
      #  install dependencies 
      #----------------------------------------------
      - name: Install dependencies
        run: |
          pip install -U pip 
          pip install mkdocs
          pip install linkml
        
      #----------------------------------------------
      #  generate markdown files 
      #----------------------------------------------
      - run: |
          cp src/docs/*.md docs
          gen-doc -d docs src/linkml/cellcard.yaml

      #----------------------------------------------
      #  deploy documentation 
      #----------------------------------------------
      - run: mk-docs gh-deploy
